Repository nordic96/Infinite_Challenge, pull requests merged in 2020-07, with the labels that each got.

#16 fixed phase1.py
  phase1.py
Labels: bug

#20 Another fix for some unrefactored method calls
  main.py
  phase1.py
Labels: bug, enhancement

#21 Reformat merge conflict
  .gitignore
  dataset/skull/yolov5/models/__pycache__/__init__.cpython-37.pyc
  dataset/skull/yolov5/models/__pycache__/common.cpython-37.pyc
  dataset/skull/yolov5/models/__pycache__/experimental.cpython-37.pyc
  dataset/skull/yolov5/models/__pycache__/yolo.cpython-37.pyc
  dataset/skull/yolov5/utils/__pycache__/__init__.cpython-37.pyc
  dataset/skull/yolov5/utils/__pycache__/datasets.cpython-37.pyc
  dataset/skull/yolov5/utils/__pycache__/google_utils.cpython-37.pyc
  dataset/skull/yolov5/utils/__pycache__/torch_utils.cpython-37.pyc
  dataset/skull/yolov5/utils/__pycache__/utils.cpython-37.pyc
Labels: bug

#22 Create aws.yml
  .github/workflows/aws.yml
Labels: enhancement, good first issue

#27 Dockerize application
  Dockerfile
  docker_entrypoint.sh
  model/vid_recognition.py
  phase1.py
  phase2.py
  print_results.py
Labels: enhancement

#62 Change skull model version
  infinitechallenge/model/skull_detection.py
  strings.ini
Labels: bug

#64 Add phase 1 readme
  README.md
  docs/images/CusVis_result.png
  docs/images/typical_error.png
Labels: documentation
